/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * AI Karobar accounting software API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary List all customers
 */
export const ListCustomersResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "address": zod.string(),
  "balance": zod.number(),
  "createdAt": zod.string()
})
export const ListCustomersResponse = zod.array(ListCustomersResponseItem)


/**
 * @summary Create a new customer
 */



export const CreateCustomerBody = zod.object({
  "name": zod.string().min(1),
  "phone": zod.string(),
  "address": zod.string(),
  "balance": zod.number().optional()
})


/**
 * @summary Get a customer by ID
 */
export const GetCustomerParams = zod.object({
  "id": zod.coerce.number()
})

export const GetCustomerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "address": zod.string(),
  "balance": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Update a customer
 */
export const UpdateCustomerParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateCustomerBody = zod.object({
  "name": zod.string().min(1).optional(),
  "phone": zod.string().optional(),
  "address": zod.string().optional(),
  "balance": zod.number().optional()
})

export const UpdateCustomerResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "address": zod.string(),
  "balance": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a customer
 */
export const DeleteCustomerParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all transactions
 */
export const ListTransactionsQueryParams = zod.object({
  "type": zod.enum(['income', 'expense', 'udharo']).optional(),
  "customerId": zod.coerce.number().optional()
})

export const ListTransactionsResponseItem = zod.object({
  "id": zod.number(),
  "billNo": zod.string(),
  "title": zod.string(),
  "amount": zod.number(),
  "type": zod.enum(['income', 'expense', 'udharo']),
  "date": zod.string(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().nullish(),
  "customerPhone": zod.string().nullish(),
  "paymentMode": zod.union([zod.literal('cash'),zod.literal('mobile_banking'),zod.literal('cheque'),zod.literal('wallet'),zod.literal('esewa'),zod.literal(null)]).nullish(),
  "createdAt": zod.string()
})
export const ListTransactionsResponse = zod.array(ListTransactionsResponseItem)


/**
 * @summary Create a new transaction
 */



export const CreateTransactionBody = zod.object({
  "title": zod.string().min(1),
  "amount": zod.number(),
  "type": zod.enum(['income', 'expense', 'udharo']),
  "date": zod.string(),
  "customerId": zod.number().nullish(),
  "paymentMode": zod.union([zod.literal('cash'),zod.literal('mobile_banking'),zod.literal('cheque'),zod.literal('wallet'),zod.literal('esewa'),zod.literal(null)]).nullish()
})


/**
 * @summary Get a transaction by ID
 */
export const GetTransactionParams = zod.object({
  "id": zod.coerce.number()
})

export const GetTransactionResponse = zod.object({
  "id": zod.number(),
  "billNo": zod.string(),
  "title": zod.string(),
  "amount": zod.number(),
  "type": zod.enum(['income', 'expense', 'udharo']),
  "date": zod.string(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().nullish(),
  "customerPhone": zod.string().nullish(),
  "paymentMode": zod.union([zod.literal('cash'),zod.literal('mobile_banking'),zod.literal('cheque'),zod.literal('wallet'),zod.literal('esewa'),zod.literal(null)]).nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Update a transaction
 */
export const UpdateTransactionParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateTransactionBody = zod.object({
  "title": zod.string().min(1).optional(),
  "amount": zod.number().optional(),
  "type": zod.enum(['income', 'expense', 'udharo']).optional(),
  "date": zod.string().optional(),
  "customerId": zod.number().nullish(),
  "paymentMode": zod.union([zod.literal('cash'),zod.literal('mobile_banking'),zod.literal('cheque'),zod.literal('wallet'),zod.literal('esewa'),zod.literal(null)]).nullish()
})

export const UpdateTransactionResponse = zod.object({
  "id": zod.number(),
  "billNo": zod.string(),
  "title": zod.string(),
  "amount": zod.number(),
  "type": zod.enum(['income', 'expense', 'udharo']),
  "date": zod.string(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().nullish(),
  "customerPhone": zod.string().nullish(),
  "paymentMode": zod.union([zod.literal('cash'),zod.literal('mobile_banking'),zod.literal('cheque'),zod.literal('wallet'),zod.literal('esewa'),zod.literal(null)]).nullish(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a transaction
 */
export const DeleteTransactionParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary List all products
 */
export const ListProductsResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "stock": zod.number(),
  "sellingPrice": zod.number(),
  "purchasePrice": zod.number(),
  "createdAt": zod.string()
})
export const ListProductsResponse = zod.array(ListProductsResponseItem)


/**
 * @summary Create a new product
 */



export const CreateProductBody = zod.object({
  "name": zod.string().min(1),
  "stock": zod.number(),
  "sellingPrice": zod.number(),
  "purchasePrice": zod.number()
})


/**
 * @summary Get a product by ID
 */
export const GetProductParams = zod.object({
  "id": zod.coerce.number()
})

export const GetProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "stock": zod.number(),
  "sellingPrice": zod.number(),
  "purchasePrice": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Update a product
 */
export const UpdateProductParams = zod.object({
  "id": zod.coerce.number()
})




export const UpdateProductBody = zod.object({
  "name": zod.string().min(1).optional(),
  "stock": zod.number().optional(),
  "sellingPrice": zod.number().optional(),
  "purchasePrice": zod.number().optional()
})

export const UpdateProductResponse = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "stock": zod.number(),
  "sellingPrice": zod.number(),
  "purchasePrice": zod.number(),
  "createdAt": zod.string()
})


/**
 * @summary Delete a product
 */
export const DeleteProductParams = zod.object({
  "id": zod.coerce.number()
})


/**
 * @summary Get dashboard summary statistics
 */
export const GetDashboardSummaryResponse = zod.object({
  "todaySales": zod.number(),
  "monthlySales": zod.number(),
  "todayPurchase": zod.number(),
  "monthlyPurchase": zod.number(),
  "todayExpenses": zod.number(),
  "monthlyExpenses": zod.number(),
  "totalUdharo": zod.number(),
  "totalCustomers": zod.number()
})


/**
 * @summary Get recent transactions for dashboard
 */
export const GetRecentTransactionsResponseItem = zod.object({
  "id": zod.number(),
  "billNo": zod.string(),
  "title": zod.string(),
  "amount": zod.number(),
  "type": zod.enum(['income', 'expense', 'udharo']),
  "date": zod.string(),
  "customerId": zod.number().nullish(),
  "customerName": zod.string().nullish(),
  "customerPhone": zod.string().nullish(),
  "paymentMode": zod.union([zod.literal('cash'),zod.literal('mobile_banking'),zod.literal('cheque'),zod.literal('wallet'),zod.literal('esewa'),zod.literal(null)]).nullish(),
  "createdAt": zod.string()
})
export const GetRecentTransactionsResponse = zod.array(GetRecentTransactionsResponseItem)


/**
 * @summary Get top customers by udharo balance
 */
export const GetTopCustomersResponseItem = zod.object({
  "id": zod.number(),
  "name": zod.string(),
  "phone": zod.string(),
  "address": zod.string(),
  "balance": zod.number(),
  "createdAt": zod.string()
})
export const GetTopCustomersResponse = zod.array(GetTopCustomersResponseItem)


